#!/usr/bin/env python3
"""
Loader for the BB India org & territory export (bb_org.json).

This file is regenerated by hand and dropped in, so it is treated as UNTRUSTED
INPUT: every assumption about its shape is checked at load time and violations are
collected as issues rather than raised. A malformed org file must degrade the report
to "no org data", never take the ETL down — the field metrics are the product; the
org structure is an enrichment.

Shape it expects
    {"meta": {...}, "states": [{"state": "...", "roots": [node, ...]}, ...]}
    node = {"employee": {empCode,name,staffType,level,territory,doj,hq,state,zone,division},
            "geography": {"name","pincodes":[...]}?, "geographyMapped": bool?,
            "subordinates": [node, ...]?}

Two structural facts about the export that matter:

  1. It is a FOREST, one tree per state, and people who cover several states appear
     once under each. 443 walked nodes are 420 distinct people. Deduping by employee
     code is therefore mandatory; without it the org tree would draw Ranjith Menon
     seven times and every roll-up above him would be multiplied.

  2. Vacant positions carry a BLANK employee code. They are real and worth seeing —
     they are territories with pincodes and no one working them — so they get stable
     synthetic ids (VAC:<state>:<territory>) rather than being dropped or, worse,
     silently colliding with each other on the empty-string key.

Run standalone for a coverage report:
    python3 org.py bb_org.json [roster.json]
"""
import json, os, re, sys, datetime

REQUIRED_EMP = ("empCode", "name", "staffType")
LEVEL_NAME = {0: "HO", 1: "ZBM", 2: "RBM", 3: "ABM", 4: "BO"}


def norm(code):
    """Join key. Codes arrive as EC7019, ec7019, 'EC 7019' — one of the 420 really is
    lowercase, and an exact-match join would have dropped that person silently."""
    return re.sub(r"[^A-Z0-9]", "", str(code or "").upper())


def parse_doj(s):
    s = (s or "").strip()
    if not s:
        return ""
    for f in ("%d/%b/%y", "%d/%b/%Y", "%d-%b-%y", "%d-%b-%Y",
              "%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y"):
        try:
            d = datetime.datetime.strptime(s, f).date()
            # a two-digit year that lands in the future is a century error, not a hire
            if d.year > datetime.date.today().year + 1:
                d = d.replace(year=d.year - 100)
            return d.isoformat()
        except ValueError:
            pass
    return ""


def load_org(path):
    """Returns (org, issues). org is {} when the file is absent or unusable."""
    issues = []
    if not path or not os.path.exists(path):
        return {}, ["org file not found at %s — org features are off" % path]
    try:
        raw = json.load(open(path, encoding="utf-8"))
    except Exception as e:
        return {}, ["org file is not valid JSON (%s) — org features are off" % str(e)[:120]]
    if not isinstance(raw, dict) or not isinstance(raw.get("states"), list):
        return {}, ["org file has no states[] array — org features are off"]

    people, vac, seen_states, walked_by = {}, [], {}, {}
    walked = 0

    def visit(node, state, parent_key, depth):
        nonlocal walked
        if not isinstance(node, dict):
            issues.append("non-object node under %s" % state)
            return
        e = node.get("employee")
        if not isinstance(e, dict):
            issues.append("node without an employee block under %s" % state)
            return
        walked += 1
        walked_by[str(e.get("staffType") or "?").upper()] = \
            walked_by.get(str(e.get("staffType") or "?").upper(), 0) + 1
        missing = [k for k in REQUIRED_EMP if k not in e]
        if missing:
            issues.append("employee missing %s under %s" % (",".join(missing), state))

        code = str(e.get("empCode") or "").strip()
        name = str(e.get("name") or "").strip()
        is_vac = not code
        key = norm(code) if code else "VAC:%s:%s" % (state, (e.get("territory") or name or len(vac)))

        geo = node.get("geography") if isinstance(node.get("geography"), dict) else {}
        pins = [str(p) for p in (geo.get("pincodes") or []) if str(p).strip()]

        rec = people.get(key)
        if rec is None:
            lvl = e.get("level")
            lvl = lvl if isinstance(lvl, int) else -1
            rec = people[key] = dict(
                key=key, code=code, name=name,
                stf=str(e.get("staffType") or LEVEL_NAME.get(lvl, "?")),
                lvl=lvl, terr=str(e.get("territory") or "").strip(),
                hq=str(e.get("hq") or "").strip(), st=str(e.get("state") or "").strip(),
                zn=str(e.get("zone") or "").strip(), div=str(e.get("division") or "").strip(),
                doj=parse_doj(e.get("doj")), parent=parent_key, vacant=is_vac,
                pins=pins, geoMapped=bool(node.get("geographyMapped")),
                states=[], depth=depth)
            if is_vac:
                vac.append(key)
        else:
            # already seen in another state tree: same person, different branch.
            # Keep the shallowest parent — that is their real position; the deeper
            # appearances are the same person shown again inside each state.
            if parent_key and rec["parent"] and parent_key != rec["parent"]:
                if depth < rec["depth"]:
                    rec["parent"], rec["depth"] = parent_key, depth
            elif parent_key and not rec["parent"]:
                rec["parent"], rec["depth"] = parent_key, depth
            if pins and not rec["pins"]:
                rec["pins"] = pins
        if state and state not in rec["states"]:
            rec["states"].append(state)
        seen_states[state] = seen_states.get(state, 0) + 1

        kids = node.get("subordinates")
        if kids is None:
            kids = []
        if not isinstance(kids, list):
            issues.append("subordinates is not a list for %s" % (name or code))
            kids = []
        for k in kids:
            visit(k, state, key, depth + 1)

    for s in raw["states"]:
        if not isinstance(s, dict):
            issues.append("non-object entry in states[]")
            continue
        state = str(s.get("state") or "").strip() or "?"
        roots = s.get("roots")
        if not isinstance(roots, list):
            issues.append("state %s has no roots[]" % state)
            continue
        for r in roots:
            visit(r, state, "", 0)

    # ---- integrity: every parent must resolve, and no chain may loop -------------
    for k, p in list(people.items()):
        if p["parent"] and p["parent"] not in people:
            issues.append("%s (%s) reports to an unknown code — treated as a root"
                          % (p["name"], p["code"] or "vacant"))
            p["parent"] = ""
    for k in people:
        chain, cur = set(), k
        while cur:
            if cur in chain:
                issues.append("reporting loop at %s — link cut" % people[k]["name"])
                people[k]["parent"] = ""
                break
            chain.add(cur)
            cur = people[cur]["parent"]

    # recompute depth from the deduped graph rather than trusting the walk order
    for k, p in people.items():
        d, cur = 0, p["parent"]
        while cur and d < 50:
            d += 1
            cur = people[cur]["parent"]
        p["depth"] = d

    dup = walked - len(people)
    meta = raw.get("meta") if isinstance(raw.get("meta"), dict) else {}

    # ---- does the file agree with itself? ---------------------------------------
    # meta.stats is written by the generator, the tree is the actual content. When
    # they disagree the generator has drifted from what it emits, and the safest
    # assumption is that the tree is right and the summary is stale. Worth saying
    # out loud either way: a silent mismatch here would quietly misstate headcount.
    from collections import Counter
    found = Counter(p["stf"].upper() for p in people.values() if not p["vacant"])
    declared = meta.get("stats") if isinstance(meta.get("stats"), dict) else {}
    notes = []
    for key, stf in (("hoCount", "HO"), ("zbmCount", "ZBM"), ("rbmCount", "RBM"),
                     ("abmCount", "ABM"), ("boCount", "BO"), ("dieticianCount", "DIETICIAN")):
        if not isinstance(declared.get(key), int):
            continue
        dist, walk_n = found.get(stf, 0), walked_by.get(stf, 0)
        if declared[key] == dist:
            continue
        if declared[key] == walk_n:
            # benign: the generator counts each state appearance, we count people
            notes.append("%s: file says %d (one per state appearance), %d distinct people"
                         % (stf, declared[key], dist))
        else:
            issues.append("meta.stats says %d %s, but the tree holds %d distinct "
                          "(%d appearances) — the summary block has drifted from the data"
                          % (declared[key], stf, dist, walk_n))
    if isinstance(declared.get("totalEmployees"), int):
        real = sum(1 for p in people.values() if not p["vacant"])
        if declared["totalEmployees"] != real:
            notes.append("headcount: file says %d, the tree holds %d distinct people "
                         "plus %d vacancies" % (declared["totalEmployees"], real, len(vac)))
    org = dict(
        people=people,
        vacancies=vac,
        meta=dict(
            division=meta.get("division", ""), zone=meta.get("zone", ""),
            country=meta.get("country", ""),
            levelHierarchy=meta.get("levelHierarchy", {}),
            declaredStats=meta.get("stats", {}),
            walked=walked, people=len(people), duplicates=dup,
            vacancies=len(vac), states=seen_states,
            maxDepth=max([p["depth"] for p in people.values()] or [0]),
            pincodes=len({p2 for p in people.values() for p2 in p["pins"]}),
            withDoj=sum(1 for p in people.values() if p["doj"]),
            fileMtime=datetime.datetime.fromtimestamp(
                os.path.getmtime(path)).date().isoformat(),
        ),
        issues=issues, notes=notes,
    )
    return org, issues


def match_roster(org, codes):
    """Join report against a roster of employee codes. Returns a plain dict so the
    ETL can log it and the report can show it — coverage that nobody can see is
    coverage nobody will notice going wrong."""
    if not org:
        return dict(matched=0, rosterOnly=list(codes), orgOnly=[], rate=0)
    on = {k: p for k, p in org["people"].items() if not p["vacant"]}
    rn = {norm(c): c for c in codes}
    matched = sorted(set(on) & set(rn))
    return dict(
        matched=len(matched),
        rosterOnly=sorted(rn[c] for c in set(rn) - set(on)),
        orgOnly=sorted(on[c]["code"] for c in set(on) - set(rn)),
        rate=round(100.0 * len(matched) / max(1, len(rn)), 1),
    )


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "bb_org.json")
    org, issues = load_org(path)
    if not org:
        print("FAILED:", *issues, sep="\n  ")
        sys.exit(1)
    m = org["meta"]
    print("org file: %s (as of %s)" % (os.path.basename(path), m["fileMtime"]))
    print("  %-26s %s" % ("division / zone", (m["division"] or "?") + " / " + (m["zone"] or "?")))
    print("  %-26s %d walked -> %d distinct (%d repeats across states)"
          % ("people", m["walked"], m["people"], m["duplicates"]))
    print("  %-26s %d" % ("vacant positions", m["vacancies"]))
    print("  %-26s %d" % ("max depth", m["maxDepth"]))
    print("  %-26s %d" % ("distinct pincodes", m["pincodes"]))
    print("  %-26s %d of %d" % ("with a date of joining", m["withDoj"], m["people"]))
    from collections import Counter
    print("  %-26s %s" % ("by staff type",
          dict(Counter(p["stf"] for p in org["people"].values()))))
    print("  %-26s %s" % ("declared vs found",
          "declared %s, found %d" % (m["declaredStats"].get("totalEmployees", "?"), m["people"])))
    if org.get("notes"):
        print("\nnotes (expected differences, not errors):")
        for n in org["notes"]:
            print("  -", n)
    if issues:
        print("\nissues (%d):" % len(issues))
        for i in issues[:20]:
            print("  -", i)
    if len(sys.argv) > 2:
        roster = json.load(open(sys.argv[2], encoding="utf-8"))
        codes = list(roster) if isinstance(roster, dict) else [
            r.get("employeeCode") or r.get("c") for r in roster]
        r = match_roster(org, [c for c in codes if c])
        print("\njoin against %s (%d codes):" % (os.path.basename(sys.argv[2]), len(codes)))
        print("  matched            %d (%.1f%% of the roster)" % (r["matched"], r["rate"]))
        print("  in roster, not org %d" % len(r["rosterOnly"]))
        print("  in org, not roster %d  %s" % (len(r["orgOnly"]), r["orgOnly"][:8]))
